spring:
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate.ddl-auto: update
    show-sql: true

server.port: 8080
